services:
  app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis
      - mongo
    restart: unless-stopped

  redis:
    image: "redis:alpine"
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    restart: unless-stopped

  mongo:
    image: "mongo:latest"
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
